server:
  port: 9090
spring:
  application:
    name: Dubbo-Server


dubbo:
  application:
    id: Dubbo-Server
    name: Dubbo-Server
  registry:
    protocol: zookeeper
    address: localhost:2181
  protocol:
#    id: dubbo
    name: dubbo
    port: 20880