server:
  port: 9091

spring:
  application:
    name: Dubbo-Client


dubbo:
  application:
    id: Dubbo-Client
    name: Dubbo-Client
  registry:
    protocol: zookeeper
    address: localhost:2181
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: 20880